import type { Transaction } from "@/features/dashboard/types";

export const ALL_TRANSACTIONS: Transaction[] = [
  {
    id: "t1",
    date: "2026-05-01",
    description: "Salary May",
    category: "Income",
    amount: 4_200.0,
    currency: "USD",
    type: "income",
    account: "Chase Checking",
  },
  {
    id: "t2",
    date: "2026-04-30",
    description: "Rent",
    category: "Housing",
    amount: -1_200.0,
    currency: "USD",
    type: "expense",
    account: "Chase Checking",
  },
  {
    id: "t3",
    date: "2026-04-29",
    description: "BTC Purchase",
    category: "Crypto",
    amount: -560.0,
    currency: "USD",
    type: "crypto",
    account: "Coinbase",
  },
  {
    id: "t4",
    date: "2026-04-28",
    description: "Grocery Store",
    category: "Food",
    amount: -145.3,
    currency: "USD",
    type: "expense",
    account: "Chase Checking",
  },
  {
    id: "t5",
    date: "2026-04-27",
    description: "Transfer to Savings",
    category: "Transfer",
    amount: -2_000.0,
    currency: "USD",
    type: "transfer",
    account: "Chase Checking",
  },
  {
    id: "t6",
    date: "2026-04-26",
    description: "Freelance Project",
    category: "Income",
    amount: 2_200.0,
    currency: "USD",
    type: "income",
    account: "Chase Checking",
  },
  {
    id: "t7",
    date: "2026-04-25",
    description: "Netflix",
    category: "Entertainment",
    amount: -15.99,
    currency: "USD",
    type: "expense",
    account: "Chase Checking",
  },
  {
    id: "t8",
    date: "2026-04-24",
    description: "Doctor Visit",
    category: "Health",
    amount: -80.0,
    currency: "USD",
    type: "expense",
    account: "Chase Checking",
  },
  {
    id: "t9",
    date: "2026-04-22",
    description: "ETH Purchase",
    category: "Crypto",
    amount: -320.0,
    currency: "USD",
    type: "crypto",
    account: "Coinbase",
  },
  {
    id: "t10",
    date: "2026-04-20",
    description: "Electricity Bill",
    category: "Utilities",
    amount: -95.0,
    currency: "USD",
    type: "expense",
    account: "Chase Checking",
  },
  {
    id: "t11",
    date: "2026-04-18",
    description: "Gym Membership",
    category: "Health",
    amount: -45.0,
    currency: "USD",
    type: "expense",
    account: "Chase Checking",
  },
  {
    id: "t12",
    date: "2026-04-15",
    description: "Dividend Q1",
    category: "Income",
    amount: 380.0,
    currency: "USD",
    type: "income",
    account: "Brokerage",
  },
];

export const TX_ACCOUNTS = [
  "Chase Checking",
  "Chase Savings",
  "Coinbase",
  "Brokerage",
];
